# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactV1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formContact(object):
    def setupUi(self, formContact):
        formContact.setObjectName("formContact")
        formContact.resize(523, 518)
        self.horizontalLayout = QtWidgets.QHBoxLayout(formContact)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupboxButtons = QtWidgets.QGroupBox(formContact)
        self.groupboxButtons.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupboxButtons.setObjectName("groupboxButtons")
        self.formLayout = QtWidgets.QFormLayout(self.groupboxButtons)
        self.formLayout.setObjectName("formLayout")
        self.labelFirstName = QtWidgets.QLabel(self.groupboxButtons)
        self.labelFirstName.setObjectName("labelFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFirstName)
        self.inputFirstName = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputFirstName.setObjectName("inputFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputFirstName)
        self.labelLastName = QtWidgets.QLabel(self.groupboxButtons)
        self.labelLastName.setObjectName("labelLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelLastName)
        self.inputLastName = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputLastName.setObjectName("inputLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputLastName)
        self.lavelMiddleNam = QtWidgets.QLabel(self.groupboxButtons)
        self.lavelMiddleNam.setObjectName("lavelMiddleNam")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lavelMiddleNam)
        self.inputMiddleName = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputMiddleName.setObjectName("inputMiddleName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputMiddleName)
        self.labelKnownAs = QtWidgets.QLabel(self.groupboxButtons)
        self.labelKnownAs.setObjectName("labelKnownAs")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelKnownAs)
        self.inputKnownAs = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputKnownAs.setObjectName("inputKnownAs")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputKnownAs)
        self.labelHouseName = QtWidgets.QLabel(self.groupboxButtons)
        self.labelHouseName.setObjectName("labelHouseName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelHouseName)
        self.inputHouseNumber = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputHouseNumber.setObjectName("inputHouseNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inputHouseNumber)
        self.labelStreetName = QtWidgets.QLabel(self.groupboxButtons)
        self.labelStreetName.setObjectName("labelStreetName")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStreetName)
        self.inputStreet = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputStreet.setObjectName("inputStreet")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputStreet)
        self.labelTownName = QtWidgets.QLabel(self.groupboxButtons)
        self.labelTownName.setObjectName("labelTownName")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTownName)
        self.inputTown = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputTown.setObjectName("inputTown")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.inputTown)
        self.labelPostalTown = QtWidgets.QLabel(self.groupboxButtons)
        self.labelPostalTown.setObjectName("labelPostalTown")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelPostalTown)
        self.inputPostalTown = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputPostalTown.setObjectName("inputPostalTown")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inputPostalTown)
        self.labelPostCode = QtWidgets.QLabel(self.groupboxButtons)
        self.labelPostCode.setObjectName("labelPostCode")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelPostCode)
        self.inputPostCode = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputPostCode.setObjectName("inputPostCode")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.inputPostCode)
        self.labelTelephone = QtWidgets.QLabel(self.groupboxButtons)
        self.labelTelephone.setObjectName("labelTelephone")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelTelephone)
        self.inputTelephone = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputTelephone.setObjectName("inputTelephone")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.inputTelephone)
        self.labelMobile = QtWidgets.QLabel(self.groupboxButtons)
        self.labelMobile.setObjectName("labelMobile")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelMobile)
        self.inputMobile = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputMobile.setObjectName("inputMobile")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.inputMobile)
        self.labelEmail = QtWidgets.QLabel(self.groupboxButtons)
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelEmail)
        self.inputEmail = QtWidgets.QLineEdit(self.groupboxButtons)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.inputEmail)
        self.horizontalLayout.addWidget(self.groupboxButtons)
        self.groupBox = QtWidgets.QGroupBox(formContact)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonSubmitAdd = QtWidgets.QPushButton(self.groupBox)
        self.buttonSubmitAdd.setObjectName("buttonSubmitAdd")
        self.verticalLayout.addWidget(self.buttonSubmitAdd)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(formContact)
        QtCore.QMetaObject.connectSlotsByName(formContact)

    def retranslateUi(self, formContact):
        _translate = QtCore.QCoreApplication.translate
        formContact.setWindowTitle(_translate("formContact", "Contact"))
        self.groupboxButtons.setTitle(_translate("formContact", "Contact Details"))
        self.labelFirstName.setText(_translate("formContact", "First Name"))
        self.labelLastName.setText(_translate("formContact", "Last Name"))
        self.lavelMiddleNam.setText(_translate("formContact", "Middle Names"))
        self.labelKnownAs.setText(_translate("formContact", "Known As/Nickname"))
        self.labelHouseName.setText(_translate("formContact", "House Number/Name"))
        self.labelStreetName.setText(_translate("formContact", "Street"))
        self.labelTownName.setText(_translate("formContact", "Town"))
        self.labelPostalTown.setText(_translate("formContact", "Postal Town"))
        self.labelPostCode.setText(_translate("formContact", "PostCode"))
        self.labelTelephone.setText(_translate("formContact", "Telephone"))
        self.labelMobile.setText(_translate("formContact", "Mobile"))
        self.labelEmail.setText(_translate("formContact", "E-Mail"))
        self.groupBox.setTitle(_translate("formContact", "Actions"))
        self.buttonSubmitAdd.setText(_translate("formContact", "Add"))

