# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactV1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formContact(object):
    def setupUi(self, formContact):
        formContact.setObjectName("formContact")
        formContact.resize(523, 518)
        self.horizontalLayout = QtWidgets.QHBoxLayout(formContact)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(formContact)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputFirstName = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputFirstName.setObjectName("inputFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputFirstName)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.inputLastName = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputLastName.setObjectName("inputLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputLastName)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.inputMiddleName = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputMiddleName.setObjectName("inputMiddleName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputMiddleName)
        self.inputKnownAs_2 = QtWidgets.QLabel(self.groupBox_2)
        self.inputKnownAs_2.setObjectName("inputKnownAs_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.inputKnownAs_2)
        self.inputKnownAs = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputKnownAs.setObjectName("inputKnownAs")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputKnownAs)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.inputHouseNumber = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputHouseNumber.setObjectName("inputHouseNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inputHouseNumber)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.inputStreet = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputStreet.setObjectName("inputStreet")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputStreet)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.inputTown = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputTown.setObjectName("inputTown")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.inputTown)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.inputPostalTown = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputPostalTown.setObjectName("inputPostalTown")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inputPostalTown)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.inputPostCode = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputPostCode.setObjectName("inputPostCode")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.inputPostCode)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.inputTelephone = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputTelephone.setObjectName("inputTelephone")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.inputTelephone)
        self.inputMobile = QtWidgets.QLabel(self.groupBox_2)
        self.inputMobile.setObjectName("inputMobile")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.inputMobile)
        self.inputFirstName_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputFirstName_3.setObjectName("inputFirstName_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.inputFirstName_3)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.inputEmail = QtWidgets.QLineEdit(self.groupBox_2)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.inputEmail)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(formContact)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonSubmitAdd = QtWidgets.QPushButton(self.groupBox)
        self.buttonSubmitAdd.setObjectName("buttonSubmitAdd")
        self.verticalLayout.addWidget(self.buttonSubmitAdd)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(formContact)
        QtCore.QMetaObject.connectSlotsByName(formContact)

    def retranslateUi(self, formContact):
        _translate = QtCore.QCoreApplication.translate
        formContact.setWindowTitle(_translate("formContact", "Contact"))
        self.groupBox_2.setTitle(_translate("formContact", "Contact Details"))
        self.label.setText(_translate("formContact", "First Name"))
        self.label_2.setText(_translate("formContact", "Last Name"))
        self.label_6.setText(_translate("formContact", "Middle Names"))
        self.inputKnownAs_2.setText(_translate("formContact", "Known As/Nickname"))
        self.label_7.setText(_translate("formContact", "House Number/Name"))
        self.label_5.setText(_translate("formContact", "Street"))
        self.label_9.setText(_translate("formContact", "Town"))
        self.label_8.setText(_translate("formContact", "Postal Town"))
        self.label_11.setText(_translate("formContact", "PostCode"))
        self.label_10.setText(_translate("formContact", "Telephone"))
        self.inputMobile.setText(_translate("formContact", "Mobile"))
        self.label_12.setText(_translate("formContact", "E-Mail"))
        self.groupBox.setTitle(_translate("formContact", "Actions"))
        self.buttonSubmitAdd.setText(_translate("formContact", "Add"))

