# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRM-V1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.People = QtWidgets.QWidget()
        self.People.setObjectName("People")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.People)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.People)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.Buttons = QtWidgets.QGroupBox(self.People)
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonAdd = QtWidgets.QPushButton(self.Buttons)
        self.buttonAdd.setObjectName("buttonAdd")
        self.verticalLayout.addWidget(self.buttonAdd)
        self.buttonEdit = QtWidgets.QPushButton(self.Buttons)
        self.buttonEdit.setObjectName("buttonEdit")
        self.verticalLayout.addWidget(self.buttonEdit)
        self.buttonRemove = QtWidgets.QPushButton(self.Buttons)
        self.buttonRemove.setObjectName("buttonRemove")
        self.verticalLayout.addWidget(self.buttonRemove)
        self.buttonFind = QtWidgets.QPushButton(self.Buttons)
        self.buttonFind.setObjectName("buttonFind")
        self.verticalLayout.addWidget(self.buttonFind)
        self.buttonLoad = QtWidgets.QPushButton(self.Buttons)
        self.buttonLoad.setObjectName("buttonLoad")
        self.verticalLayout.addWidget(self.buttonLoad)
        self.buttonSave = QtWidgets.QPushButton(self.Buttons)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)
        self.buttonExport = QtWidgets.QPushButton(self.Buttons)
        self.buttonExport.setObjectName("buttonExport")
        self.verticalLayout.addWidget(self.buttonExport)
        self.horizontalLayout.addWidget(self.Buttons, 0, QtCore.Qt.AlignTop)
        self.Buttons.raise_()
        self.tableView.raise_()
        self.tabWidget.addTab(self.People, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Buttons.setTitle(_translate("MainWindow", "Buttons"))
        self.buttonAdd.setText(_translate("MainWindow", "Add"))
        self.buttonEdit.setText(_translate("MainWindow", "Edit"))
        self.buttonRemove.setText(_translate("MainWindow", "Remove"))
        self.buttonFind.setText(_translate("MainWindow", "Find"))
        self.buttonLoad.setText(_translate("MainWindow", "Load"))
        self.buttonSave.setText(_translate("MainWindow", "Save"))
        self.buttonExport.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.People), _translate("MainWindow", "People"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))

